fix workspace in github actions for ad hoc environments

diff --git a/.github/workflows/ad_hoc_env_create_update.yml b/.github/workflows/ad_hoc_env_create_update.yml
--- a/.github/workflows/ad_hoc_env_create_update.yml
+++ b/.github/workflows/ad_hoc_env_create_update.yml
@@ -109,10 +109,8 @@ jobs:
 
         run: |
 
-          # set the terraform workspace
-          export TF_WORKSPACE=$WORKSPACE
           # set the relative path of the .tfvars file corresponding to the workspace
-          export VAR_FILE=envs/${TF_WORKSPACE}.tfvars
+          export VAR_FILE=envs/${WORKSPACE}.tfvars
 
           # init
           terraform -chdir=terraform/live/ad-hoc \
@@ -123,6 +121,12 @@ jobs:
             -backend-config="key=terraform.tfstate" \
             -backend-config="region=${TF_BACKEND_REGION}" \
             -backend-config="workspace_key_prefix=ad-hoc-envs"
+
+          # create the workspace if it doesn't exist already
+          terraform workspace create ${WORKSPACE} || echo "Workspace ${WORKSPACE} already exists or cannot be created"
+
+          # set the TF_WORKSPACE environment variable
+          export TF_WORKSPACE=$WORKSPACE
 
           # plan
           terraform -chdir=terraform/live/ad-hoc \
diff --git a/.github/workflows/ad_hoc_env_destroy.yml b/.github/workflows/ad_hoc_env_destroy.yml
--- a/.github/workflows/ad_hoc_env_destroy.yml
+++ b/.github/workflows/ad_hoc_env_destroy.yml
@@ -67,8 +67,6 @@ jobs:
           TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
 
         run: |
-          # set the terraform workspace
-          export TF_WORKSPACE=$WORKSPACE
 
           terraform -chdir=terraform/live/ad-hoc \
             init \
@@ -78,5 +76,11 @@ jobs:
             -backend-config="key=terraform.tfstate" \
             -backend-config="region=${TF_BACKEND_REGION}" \
             -backend-config="workspace_key_prefix=ad-hoc-envs"
+
+          # create the workspace if it doesn't exist already
+          terraform workspace create ${WORKSPACE} || echo "Workspace ${WORKSPACE} already exists or cannot be created"
+
+          # set the terraform workspace
+          export TF_WORKSPACE=$WORKSPACE
 
           terraform -chdir=terraform/live/ad-hoc destroy -auto-approve
