feat(tf): debug

diff --git a/.github/workflows/prod_base_create_update_terraform.yml b/.github/workflows/prod_base_create_update_terraform.yml
--- a/.github/workflows/prod_base_create_update_terraform.yml
+++ b/.github/workflows/prod_base_create_update_terraform.yml
@@ -76,18 +76,19 @@ jobs:
             -no-color \
             -out=tfplan \
             -var-file=$VAR_FILE
+
       - name: ls
         run: |
           ls -al
 
       # https://github.com/actions/upload-artifact/issues?q=is%3Aissue+is%3Aopen+working-directory
-      - name: Save synth output to artifact
+      - name: Upload artifacts
         uses: actions/upload-artifact@v3
         with:
           name: tfplan
-          path: "iac/terraform/live/prod/base/tfplan"
+          path: "iac/terraform/live/prod/base/"
 
-
+  # https://developer.hashicorp.com/terraform/tutorials/automation/automate-terraform#plan-and-apply-on-different-machines
   prod_base_deploy:
     name: "Prod base deploy"
     environment: prod
@@ -104,6 +105,10 @@ jobs:
           name: tfplan
           path: "iac/terraform/live/prod/base"
 
+      - name: ls
+        run: |
+          ls -al
+
       - uses: hashicorp/setup-terraform@v1
         with:
           terraform_version: 1.3.6
@@ -118,4 +123,19 @@ jobs:
 
       - name: terraform apply
         run: |
+
+          # terraform \
+          #   init \
+          #   -backend-config="bucket=${TF_BACKEND_BUCKET}" \
+          #   -backend-config="dynamodb_table=${TF_BACKEND_DYNAMODB_TABLE}" \
+          #   -backend-config="key=terraform.tfstate" \
+          #   -backend-config="region=${TF_BACKEND_REGION}" \
+          #   -backend-config="workspace_key_prefix=prod/base"
+
+          # create the workspace if it doesn't exist already
+          terraform workspace new ${WORKSPACE} || echo "Workspace ${WORKSPACE} already exists or cannot be created"
+
+          # set the TF_WORKSPACE environment variable
+          export TF_WORKSPACE=$WORKSPACE
+
           terraform apply -auto-approve "tfplan"
