feat(destroy): fixes for prod base destroy

diff --git a/.github/workflows/prod_base_destroy_terraform.yml b/.github/workflows/prod_base_destroy_terraform.yml
--- a/.github/workflows/prod_base_destroy_terraform.yml
+++ b/.github/workflows/prod_base_destroy_terraform.yml
@@ -1,5 +1,5 @@
 # github action to create or update shared resources
-name: prod | base | destroy
+name: prod | base | destroy [Terraform]
 
 on:
   workflow_dispatch:
@@ -10,13 +10,19 @@ on:
         default: 'stage'
         type: string
 
+defaults:
+  run:
+    working-directory: iac/terraform/live/prod/base
+
 jobs:
-  prod_base_destroy:
+  prod_base_destroy_plan:
     name: "Destroy prod base env [${{ github.event.inputs.workspace }}]"
-    environment: prod-base-${{ github.event.inputs.workspace }}
+    environment: prod
     runs-on: ubuntu-latest
 
     steps:
+
+      - uses: actions/checkout@v2
 
       - uses: hashicorp/setup-terraform@v1
         with:
@@ -30,26 +36,17 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
 
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-
-      - name: "terraform init and destroy for prod base env"
-        id: prod_base_destroy_terraform_init_destroy
+      - name: "terraform init"
+        id: terraform_init
         env:
           TF_BACKEND_BUCKET: ${{ secrets.TF_BACKEND_BUCKET }}
           TF_BACKEND_REGION: ${{ secrets.TF_BACKEND_REGION }}
           TF_BACKEND_DYNAMODB_TABLE: ${{ secrets.TF_BACKEND_DYNAMODB_TABLE }}
           WORKSPACE: ${{ github.event.inputs.workspace }}
 
-          # Terraform variables
-          TF_VAR_certificate_arn: ${{ secrets.ACM_CERTIFICATE_ARN }}
-          TF_VAR_key_name: ${{ secrets.KEY_NAME }}
-
         run: |
-          export VAR_FILE=envs/${WORKSPACE}.tfvars
 
-          terraform -chdir=iac/terraform/live/prod/base \
+          terraform \
             init \
             -backend-config="bucket=${TF_BACKEND_BUCKET}" \
             -backend-config="dynamodb_table=${TF_BACKEND_DYNAMODB_TABLE}" \
@@ -57,21 +54,70 @@ jobs:
             -backend-config="region=${TF_BACKEND_REGION}" \
             -backend-config="workspace_key_prefix=prod/base"
 
-          # create the workspace if it doesn't exist already
-          terraform workspace new ${WORKSPACE} || echo "Workspace ${WORKSPACE} already exists or cannot be created"
+      - name: "terraform plan"
+        id: terraform_plan
+        env:
+          WORKSPACE: ${{ github.event.inputs.workspace }}
+          TF_VAR_certificate_arn: ${{ secrets.ACM_CERTIFICATE_ARN }}
+          TF_VAR_key_name: ${{ secrets.KEY_NAME }}
+        run: |
 
-          # set the TF_WORKSPACE environment variable
+          terraform workspace new ${WORKSPACE} || echo "Workspace ${WORKSPACE} already exists or cannot be created"
           export TF_WORKSPACE=$WORKSPACE
 
-          terraform -chdir=iac/terraform/live/prod/base \
-            destroy \
-            -auto-approve
+          terraform \
+            plan \
+            -destroy \
+            -input=false \
+            -no-color \
+            -var-file=envs/$WORKSPACE.tfvars \
+            -out=tfplan
 
-          # switch to the default workspace
-          unset TF_WORKSPACE
-          terraform workspace select default
+      # https://github.com/actions/upload-artifact/issues?q=is%3Aissue+is%3Aopen+working-directory
+      - name: Upload tfplan artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: tfplan
+          path: "iac/terraform/live/prod/base/"
 
-          # delete the workspace
-          terraform workspace delete ${WORKSPACE}
+  prod_base_destroy_apply:
+    name: "Prod base destroy"
+    environment: prod
+    runs-on: ubuntu-latest
+    needs: prod_base_destroy_plan
+    steps:
 
-          echo "Terraform workspace ${WORKSPACE} has been deleted."
+      - uses: actions/checkout@v2
+
+      # https://github.com/actions/upload-artifact/issues?q=is%3Aissue+is%3Aopen+working-directory
+      - uses: actions/download-artifact@v3
+        with:
+          name: tfplan
+          path: "iac/terraform/live/prod/base"
+
+      - uses: hashicorp/setup-terraform@v1
+        with:
+          terraform_version: 1.3.6
+          terraform_wrapper: false
+
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+
+      - name: "terraform apply destroy prod base"
+        id: terraform_apply_destroy
+        env:
+          WORKSPACE: ${{ github.event.inputs.workspace }}
+
+        run: |
+
+          # https://github.com/hashicorp/terraform/issues/24010#issuecomment-592936990
+          chmod -R a+x ./.terraform/*
+
+          terraform workspace new ${WORKSPACE} || echo "Workspace ${WORKSPACE} already exists or cannot be created"
+          export TF_WORKSPACE=$WORKSPACE
+
+          terraform apply -auto-approve "tfplan"
