fix(actions): fix github actions for terraform shared resources destroy

diff --git a/.github/workflows/shared_resources_destroy.yml b/.github/workflows/shared_resources_destroy.yml
--- a/.github/workflows/shared_resources_destroy.yml
+++ b/.github/workflows/shared_resources_destroy.yml
@@ -47,8 +47,6 @@ jobs:
           TF_VAR_key_name: ${{ secrets.KEY_NAME }}
 
         run: |
-          # set the terraform workspace
-          export TF_WORKSPACE=$WORKSPACE
           export VAR_FILE=envs/${TF_WORKSPACE}.tfvars
 
           terraform -chdir=terraform/live/shared-resources \
@@ -58,5 +56,12 @@ jobs:
             -backend-config="key=terraform.tfstate" \
             -backend-config="region=${TF_BACKEND_REGION}" \
             -backend-config="workspace_key_prefix=shared-resources"
+
+          # create the workspace if it doesn't exist already
+          terraform workspace create ${WORKSPACE} || echo "Workspace ${WORKSPACE} already exists or cannot be created"
+
+          # set the TF_WORKSPACE environment variable
+          export TF_WORKSPACE=$WORKSPACE
+
 
           terraform -chdir=terraform/live/shared-resources destroy -auto-approve
